"""add_message_reads_table

Revision ID: e41600f8575c
Revises: 32dead81c695
Create Date: 2025-11-10 07:58:25.359169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e41600f8575c'
down_revision: Union[str, None] = '32dead81c695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_reads',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'user_id')
    )
    op.create_index('ix_message_read_user', 'message_reads', ['user_id'], unique=False)
    op.drop_index(op.f('ix_colors_id'), table_name='colors')
    op.drop_index(op.f('name'), table_name='colors')
    op.drop_table('colors')
    op.drop_index(op.f('idx_changed_at'), table_name='product_audit')
    op.drop_index(op.f('idx_product_id'), table_name='product_audit')
    op.drop_table('product_audit')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_index(op.f('name'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_product_tags_tag'), table_name='product_tags')
    op.drop_table('product_tags')
    op.drop_index(op.f('ix_product_materials_material'), table_name='product_materials')
    op.drop_table('product_materials')
    op.drop_index(op.f('ix_product_colors_color'), table_name='product_colors')
    op.drop_table('product_colors')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index(op.f('name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ft_product_search'), table_name='products', mysql_prefix='FULLTEXT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ft_product_search'), 'products', ['title', 'description'], unique=False, mysql_prefix='FULLTEXT')
    op.create_table('tags',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('name'), 'tags', ['name'], unique=True)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_table('product_colors',
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('color_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], name=op.f('product_colors_ibfk_1'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_colors_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'color_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_product_colors_color'), 'product_colors', ['color_id'], unique=False)
    op.create_table('product_materials',
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('material_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('product_materials_ibfk_1'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_materials_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'material_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_product_materials_material'), 'product_materials', ['material_id'], unique=False)
    op.create_table('product_tags',
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_tags_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('product_tags_ibfk_2'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('product_id', 'tag_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_product_tags_tag'), 'product_tags', ['tag_id'], unique=False)
    op.create_table('materials',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('name'), 'materials', ['name'], unique=True)
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_table('product_audit',
    sa.Column('audit_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action_type', mysql.ENUM('INSERT', 'UPDATE', 'DELETE'), nullable=False),
    sa.Column('old_price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('new_price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('old_status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('new_status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('old_title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('new_title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('changed_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('changed_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('audit_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_product_id'), 'product_audit', ['product_id'], unique=False)
    op.create_index(op.f('idx_changed_at'), 'product_audit', ['changed_at'], unique=False)
    op.create_table('colors',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('name'), 'colors', ['name'], unique=True)
    op.create_index(op.f('ix_colors_id'), 'colors', ['id'], unique=False)
    op.drop_index('ix_message_read_user', table_name='message_reads')
    op.drop_table('message_reads')
    # ### end Alembic commands ###
